# Generated by Django 5.1.6 on 2025-02-23 14:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('father_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=15)),
                ('village', models.CharField(blank=True, db_index=True, max_length=100)),
                ('address', models.TextField(blank=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_time', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], db_index=True, max_length=10)),
                ('milk_type', models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo'), ('cow_buffalo', 'Cow + Buffalo')], db_index=True, max_length=20)),
                ('collection_date', models.DateField(db_index=True)),
                ('base_fat_percentage', models.DecimalField(decimal_places=3, default=6.5, max_digits=4)),
                ('base_snf_percentage', models.DecimalField(decimal_places=3, default=9.0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('9.0'), message='Base SNF percentage cannot be less than 9.0'), django.core.validators.MaxValueValidator(Decimal('9.5'), message='Base SNF percentage cannot be more than 9.5')])),
                ('measured', models.CharField(choices=[('liters', 'Liters'), ('kg', 'Kg')], max_length=10)),
                ('liters', models.DecimalField(decimal_places=3, max_digits=6)),
                ('kg', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fat_percentage', models.DecimalField(decimal_places=3, max_digits=4)),
                ('fat_kg', models.DecimalField(decimal_places=3, max_digits=6)),
                ('clr', models.DecimalField(decimal_places=3, max_digits=4)),
                ('snf_percentage', models.DecimalField(decimal_places=3, max_digits=4)),
                ('snf_kg', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fat_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('snf_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('rate', models.DecimalField(db_index=True, decimal_places=3, max_digits=50)),
                ('solid_weight', models.DecimalField(blank=True, db_index=True, decimal_places=3, max_digits=50, null=True)),
                ('amount', models.DecimalField(db_index=True, decimal_places=3, max_digits=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.customer')),
            ],
            options={
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DairyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dairy_name', models.CharField(db_index=True, max_length=255)),
                ('dairy_address', models.TextField(blank=True)),
                ('rate_type', models.CharField(choices=[('fat_only', 'Fat Only'), ('fat_snf', 'Fat + SNF'), ('fat_clr', 'Fat + CLR')], db_index=True, max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dairy Information',
                'verbose_name_plural': 'Dairy Information',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketMilkPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name', 'phone'], name='collector_c_name_2644ba_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['author', 'is_active'], name='collector_c_author__f481e7_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['collection_date', 'collection_time'], name='collector_c_collect_3fda75_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['customer', 'collection_date'], name='collector_c_custome_826b31_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['author', 'is_active', 'collection_date'], name='collector_c_author__5f52a4_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['milk_type', 'collection_date'], name='collector_c_milk_ty_7ba5c5_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['rate', 'amount'], name='collector_c_rate_068452_idx'),
        ),
        migrations.AddIndex(
            model_name='dairyinformation',
            index=models.Index(fields=['dairy_name', 'rate_type'], name='collector_d_dairy_n_7f4133_idx'),
        ),
        migrations.AddIndex(
            model_name='dairyinformation',
            index=models.Index(fields=['author', 'is_active', 'created_at'], name='collector_d_author__5924d0_idx'),
        ),
        migrations.AddIndex(
            model_name='marketmilkprice',
            index=models.Index(fields=['price', 'created_at'], name='collector_m_price_6e9d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='marketmilkprice',
            index=models.Index(fields=['author', 'is_active', 'created_at'], name='collector_m_author__17dd92_idx'),
        ),
    ]
