# Generated by Django 5.1.6 on 2025-02-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='clr',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
