# Generated by Django 5.1.6 on 2025-02-23 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_alter_collection_clr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collection',
            name='collector_c_rate_068452_idx',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='rate',
            new_name='milk_rate',
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['milk_rate', 'amount'], name='collector_c_milk_ra_63d5ff_idx'),
        ),
    ]
