# Generated by Django 5.1.6 on 2025-11-28 06:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_remove_collection_collector_c_rate_068452_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FatStepUpRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'verbose_name': 'Fat Step Up Rate',
                'verbose_name_plural': 'Fat Step Up Rates',
                'ordering': ['chart', 'step'],
            },
        ),
        migrations.CreateModel(
            name='ProRataRateChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pro Rata Rate Chart',
                'verbose_name_plural': 'Pro Rata Rate Charts',
            },
        ),
        migrations.CreateModel(
            name='RawCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_time', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], db_index=True, max_length=10)),
                ('milk_type', models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo'), ('cow_buffalo', 'Cow + Buffalo')], db_index=True, max_length=20)),
                ('collection_date', models.DateField(db_index=True)),
                ('base_fat_percentage', models.DecimalField(decimal_places=3, default=6.5, max_digits=4)),
                ('base_snf_percentage', models.DecimalField(decimal_places=3, default=9.0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('8.0'), message='Base SNF percentage cannot be less than 8.0'), django.core.validators.MaxValueValidator(Decimal('9.5'), message='Base SNF percentage cannot be more than 9.5')])),
                ('measured', models.CharField(choices=[('liters', 'Liters'), ('kg', 'Kg')], max_length=10)),
                ('liters', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('kg', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('fat_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fat_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('clr', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('snf_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('snf_kg', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True)),
                ('fat_rate', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True)),
                ('snf_rate', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True)),
                ('milk_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('solid_weight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('is_milk_rate', models.BooleanField(default=False)),
                ('last_edited_at', models.DateTimeField(blank=True, help_text='When this collection was last edited', null=True)),
            ],
            options={
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SnfStepDownRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'verbose_name': 'SNF Step Down Rate',
                'verbose_name_plural': 'SNF Step Down Rates',
                'ordering': ['chart', 'step'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='YoutubeChannelLink',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_active', models.BooleanField(db_index=True, default=True)),
                        ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('link', models.URLField(blank=True, null=True)),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name='dairyinformation',
            name='collector_d_dairy_n_7f4133_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='collection',
                    name='edit_count',
                    field=models.IntegerField(default=0, help_text='Number of times this collection has been edited'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='collection',
                    name='is_pro_rata',
                    field=models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='collection',
                    name='is_raw_collection',
                    field=models.BooleanField(default=False, help_text='Whether this collection was created from a raw collection'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='collection',
                    name='last_edited_at',
                    field=models.DateTimeField(blank=True, help_text='When this collection was last edited', null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='customer',
                    name='customer_id',
                    field=models.PositiveIntegerField(db_index=True, default=0, help_text='Sequential customer number'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='dairyinformation',
                    name='base_snf',
                    field=models.DecimalField(blank=True, choices=[(8.5, 8.5), (9.0, 9.0)], db_index=True, decimal_places=3, default=9.0, max_digits=4, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name='dairyinformation',
            name='clr_conversion_factor',
            field=models.DecimalField(blank=True, choices=[(0.14, 0.14), (0.5, 0.5)], db_index=True, decimal_places=3, default=0.14, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='dairyinformation',
            name='fat_snf_ratio',
            field=models.CharField(blank=True, choices=[('60/40', '60/40'), ('52/48', '52/48')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='collection',
            name='base_snf_percentage',
            field=models.DecimalField(decimal_places=3, default=9.0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('8.0'), message='Base SNF percentage cannot be less than 8.0'), django.core.validators.MaxValueValidator(Decimal('9.5'), message='Base SNF percentage cannot be more than 9.5')]),
        ),
        migrations.AlterField(
            model_name='collection',
            name='clr',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='fat_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='collection',
            name='fat_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='collection',
            name='fat_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='collection',
            name='kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='collection',
            name='liters',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='collection',
            name='milk_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='collection',
            name='snf_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='collection',
            name='snf_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='collection',
            name='snf_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='collection',
            name='solid_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dairyinformation',
            name='dairy_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dairyinformation',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('kg_only', 'Kg Only'), ('liters_only', 'Liters Only'), ('fat_only', 'Fat Only'), ('fat_snf', 'Fat + SNF'), ('fat_clr', 'Fat + CLR')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['edit_count', 'last_edited_at'], name='collector_c_edit_co_461102_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_id'], name='collector_c_custome_d8bb79_idx'),
        ),
        migrations.AddIndex(
            model_name='dairyinformation',
            index=models.Index(fields=['dairy_name', 'rate_type', 'base_snf', 'fat_snf_ratio', 'clr_conversion_factor'], name='collector_d_dairy_n_b15e09_idx'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddConstraint(
                    model_name='collection',
                    constraint=models.CheckConstraint(
                        condition=models.Q(('base_snf_percentage__gte', Decimal('8.0')), ('base_snf_percentage__lte', Decimal('9.5'))),
                        name='collection_base_snf_between_8_0_9_5',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='fatstepuprate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prorataratechart',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fatstepuprate',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fat_step_up_rates', to='collector.prorataratechart'),
        ),
        migrations.AddField(
            model_name='rawcollection',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawcollection',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.customer'),
        ),
        migrations.AddField(
            model_name='snfstepdownrate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snfstepdownrate',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snf_step_down_rates', to='collector.prorataratechart'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='youtubechannellink',
                    name='author',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='prorataratechart',
            index=models.Index(fields=['author', 'is_active'], name='collector_p_author__c152ca_idx'),
        ),
        migrations.AddIndex(
            model_name='fatstepuprate',
            index=models.Index(fields=['chart', 'step'], name='collector_f_chart_i_a16c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='rawcollection',
            index=models.Index(fields=['collection_date', 'collection_time'], name='collector_r_collect_aa0ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='rawcollection',
            index=models.Index(fields=['customer', 'collection_date'], name='collector_r_custome_6dac89_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawcollection',
            constraint=models.CheckConstraint(condition=models.Q(('base_snf_percentage__gte', Decimal('8.0')), ('base_snf_percentage__lte', Decimal('9.5'))), name='rawcollection_base_snf_between_8_0_9_5'),
        ),
        migrations.AddIndex(
            model_name='snfstepdownrate',
            index=models.Index(fields=['chart', 'step'], name='collector_s_chart_i_e2a484_idx'),
        ),
    ]
