# Generated by Django 5.1.6 on 2025-11-28 09:26

from django.db import migrations, models


def fill_dairyinformation_defaults(apps, schema_editor):
    DairyInformation = apps.get_model('collector', 'DairyInformation')
    # Ensure no NULLs remain before making fields non-nullable
    DairyInformation.objects.filter(base_snf__isnull=True).update(base_snf=9.0)
    DairyInformation.objects.filter(clr_conversion_factor__isnull=True).update(clr_conversion_factor=0.14)
    DairyInformation.objects.filter(fat_snf_ratio__isnull=True).update(fat_snf_ratio='60/40')


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_fatstepuprate_prorataratechart_rawcollection_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_dairyinformation_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='dairyinformation',
            name='base_snf',
            field=models.DecimalField(choices=[(8.5, 8.5), (9.0, 9.0)], db_index=True, decimal_places=3, default=9.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='dairyinformation',
            name='clr_conversion_factor',
            field=models.DecimalField(choices=[(0.14, 0.14), (0.5, 0.5)], db_index=True, decimal_places=3, default=0.14, max_digits=4),
        ),
        migrations.AlterField(
            model_name='dairyinformation',
            name='fat_snf_ratio',
            field=models.CharField(choices=[('60/40', '60/40'), ('52/48', '52/48')], db_index=True, default='60/40', max_length=10),
        ),
    ]
