# Generated by Django 5.1.6 on 2025-11-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_alter_dairyinformation_base_snf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairyinformation',
            name='fat_snf_ratio',
            field=models.CharField(choices=[('60/40', '60/40'), ('52/48', '52/48')], db_index=True, default='60/40', max_length=10),
        ),
    ]
