# Generated by Django 5.1.6 on 2025-11-24 13:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_user_usernam_6d9439_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_user_email_5f6a77_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_password_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_password_token_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a 10-digit number.', regex='^(\\+91)?[1-9]\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
